import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  File,
  FileText,
  Image,
  LayoutDashboardIcon,
  Loader2,
  LogIn,
  LucideIcon,
  Plus,
  Settings,
  Trash,
  User,
  User2Icon,
  UserX2Icon,
  X,
  ArrowRightLeft,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  dashboard: LayoutDashboardIcon,
  logo: Command,
  login: LogIn,
  close: X,
  profile: User2Icon,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  employee: UserX2Icon,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  check: Check,
  arrowRightLeft: ArrowRightLeft,
};
